palette = 0=#241109
palette = 1=#b8452e
palette = 2=#a3873f
palette = 3=#c9a877
palette = 4=#a3763f
palette = 5=#8a5a6e
palette = 6=#c0a860
palette = 7=#e8e2d4
palette = 8=#6e3b22
palette = 9=#d98a6a
palette = 10=#c0a860
palette = 11=#e0c48a
palette = 12=#c9a877
palette = 13=#b07a8a
palette = 14=#d8b878
palette = 15=#f2ede1

background = #241109
foreground = #f2ede1

cursor-color = #c9a877
cursor-text = #241109

selection-background = #c9a877
selection-foreground = #241109