$color = rgba(36, 17, 9, 1)
$inner_color = rgba(78, 42, 27, 1)
$outer_color = rgba(201, 168, 119, 1)
$font_color = rgba(242, 237, 225, 1)
$placeholder_color = rgba(163, 118, 63, 1)
$check_color = rgba(217, 138, 106, 1)
